version: '3.1'

services:
  test-db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    ports:
      - 3306:3306
    volumes:
      - test-db-data:/var/lib/mysql
  postgres-db:
    image: postgres
    restart: always
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: test_db
    volumes:
      - postgres-db-data:/var/lib/postgresql/data/

volumes:
  test-db-data:
  postgres-db-data:
