version: "3.1"

services:
  test-db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    ports:
      - 3306:3306
    volumes:
      - test-db-data:/var/lib/mysql

volumes:
  test-db-data:
